name: CI

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [develop, master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Run Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd jpo-geojsonconverter/jpo-ode
          mvn install -DskipTests
          cd ../jpo-geojsonconverter
          mvn install -DskipTests
          cd $GITHUB_WORKSPACE/test-message-sender
          mvn -e -X clean install
          cd $GITHUB_WORKSPACE/jpo-conflictmonitor
          mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=usdot-jpo-ode_jpo-conflictmonitor -Dsonar.projectName=jpo-conflictmonitor -Dsonar.organization=usdot-jpo-ode -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=$GITHUB_REF_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Deploy to Nexus
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          cd jpo-geojsonconverter/jpo-ode
          mvn deploy -DskipTests -DaltDeploymentRepository=stol-maven-deps::default::https://55a4-68-183-28-222.ngrok-free.app/repository/stol-maven-deps/
          cd ../jpo-geojsonconverter
          mvn deploy -DskipTests -DaltDeploymentRepository=stol-maven-deps::default::https://55a4-68-183-28-222.ngrok-free.app/repository/stol-maven-deps/
          cd $GITHUB_WORKSPACE/test-message-sender
          mvn deploy -DskipTests -DaltDeploymentRepository=stol-maven-deps::default::https://55a4-68-183-28-222.ngrok-free.app/repository/stol-maven-deps/
          cd $GITHUB_WORKSPACE/jpo-conflictmonitor
          mvn deploy -DskipTests -DaltDeploymentRepository=stol-maven-deps::default::https://55a4-68-183-28-222.ngrok-free.app/repository/stol-maven-deps/
